### ISSUE TITLE
Organisation des boutons

### ISSUE THREAD

**Issue by dngconsulting** [dngconsulting/OpenDossard#107]
Il y a trop de boutons "Télécharger XX/YY" côte à côte dans l'écran des classements. Sur un petit écran (macbook air), les textes sont presque illisibles. Organiser les boutons avec un menu déroulant "Télécharger" puis afficher "Classement PDF", "Podium PDF", "Classement CSV", etc ...

**Comment by gcharlemagne** [comment]
Utilisation Menu et MenuItem pour regrouper les boutons téléchargements
Commit 225ee92b
