### ISSUE TITLE
Annuaire des licences - Non Licenciés

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#134]
Un coureur inscrit comme "Non Licencié" n'a pas de club rattaché. Dans la présentation graphique du nombre de participations par Club, si l'on se positionne du 01/01/2020 à ce jour on a en 5éme position avec 13 participations un "Club" sans nom ??? 
Proposition : si Fédé = "Non licencié", alors Club = "Non Licencié", de façon à ne pas avoir un Club sans nom. 
Si la proposition est validé, il faudra updater la base de données des licences

**Comment by dngconsulting** [comment]
Le problème à créer un club qui s'appelle "Non Licencié" c'est qu'il n'existe pas réellement en tant que tel et il va falloir lui donner un département, etc .. Sans compter que lorsqu'on crée un coureur NL, le champ club se masque automatiquement dans l'application alors qu'en fait on attribue réellement un club à ce coureur. Pourquoi ne pas simplement corriger le problème au niveau du graphique? Lorsque je tombe sur un coureur sans club, j'affiche dans le graphique "Non Licencié". J'ai juste une ligne de code à modifier.

**Comment by Christian-Beteille** [comment]
Parfait !!!
C’était juste pour éviter d’avoir dans le graphique l’abscisse  vide sur une position 
A+

Envoyé de mon iPhone
