### ISSUE TITLE
Classement PDF toutes les courses

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#146]
Le calcul du nombre de coureurs n'est pas réinitialisé à chaque course.
De même l'affichage du numéro de page n'est pas cohérent. Exemple : au lieu d'afficher page 1/6 l'affichage devient 1/1 puis 2/2 ...etc

**Comment by laurabouchara** [comment]
Bugs corrigés aujourd'hui dans la branche createCompetition. 

Autre bug corrigé et lié à ce ticket : le pied de page ne s'affiche pas s'il n'y a pas au moins une ligne du tableau. 
(cf. pièce jointe, page 2) 
[Clt_GrandPrixCyclistedeNoueilles_cate_2,3,4,5,C.pdf](https://github.com/dngconsulting/OpenDossard/files/6694511/Clt_GrandPrixCyclistedeNoueilles_cate_2.3.4.5.C.pdf)
