### ISSUE TITLE
OPEN DOSSARD - Annuaire des Licences

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#149]
1) Ajouter une licence : après saisie du N°de licence -->Tab amène sur le champ Fédération : donner la possibilité de saisir les premières lettres et afficher la Fédération concernée. Retour chariot valide le choix
2)Saison : limiter la saisie à un champ numérique à quatre digits, dont la valeur max n'excède pas l'année en cours

**Comment by laurabouchara** [comment]
C'est fait !
![image](https://user-images.githubusercontent.com/85871344/123429370-2c195d00-d5c7-11eb-8751-35811d5dc978.png)
