### ISSUE TITLE
Engagements Coureurs

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#178]
L'idée est de profiter de l'engagement des coureurs pour mettre à jour la fiche Licence, lorsque c'est nécessaire. 
Déjà s'affiche en rouge les informations manquantes, mais pour les "étourdis" ou les malvoyants, afficher un message dans une fenêtre : "Dans la fiche de ce coureur de informations sont absentes. Mettez les informations à jour en utilisant le lien hypertexte". Valider avec "OK"

**Comment by dngconsulting** [comment]
Pas bête. Je prends :)
