### ISSUE TITLE
Création d'une épreuve (URGENCE)

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#185]
Bug remonter par le Comité Alsace : lors de la création d'une épreuve et que le choix se porte sur un nouveau Club, la validation dudit nouveau club est inopérante. L'application reste en boucle sur la création avec le défilement des ...
On à l'impression qu'il n'accède pas à la base de données
PS J'ai débloqué la situation en leur créant le nouveau club dans DBeaver ;-)

**Comment by dngconsulting** [comment]
Vu avec Christian Pb de séquence.
