### ISSUE TITLE
Menu Engagement - Rafraichissement de la liste des Engagés (1)

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#56]
Rappel : Test effectué en Wifi domestique, donc connexion peut-être peu performante.
Objectif : supprimer de la liste d'engagement 2 coureurs : pas de problème particulier sur le premier, par contre impossible de supprimer le second : clic sur la poubelle, aucun effet. La solution : sortir de la feuille d'engagement et revenir : la feuille étant "rafraîchi" la suppression du deuxième coureur est possible. 
A vérifier le débit de la connexion Wifi, et simuler la même opération avec un débit normal

**Comment by dngconsulting** [comment]
Sur ce ticket, j'ai simulé une connexion "lente" chez moi avec un outil (Proxy Fiddler en mode simulation connexion modem). Après plusieurs désengagements en rafale, aucun souci même si, vu la connexion, on a souvent le sablier...
