### ISSUE TITLE
Menu Engagement - Rafraichissement de la liste des engagés (2)

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#57]
Rappel : Test effectué en Wifi domestique, donc connexion peut-être peu performante.
De manière aléatoire (environ tous les 10 enregistrements) le dernier dossard engagé ne s’affiche pas dans la liste. Solution : sortir du menu « Engagement » et revenir pour provoquer un rafraichissement de l’écran
A vérifier le débit de la connexion Wifi, et simuler la même opération avec un débit normal

**Comment by dngconsulting** [comment]
Duplicate of #42
