### ISSUE TITLE
Annuaire des licences - Suppression d'un coureur

### ISSUE THREAD

**Issue by Christian-Beteille** [dngconsulting/OpenDossard#70]
Scénario : création d'un nouveau coureur TARTANPION Alexandre. Ce coureur est engagé sur une épreuve et il est classé. Retour au menu "Annuaire des licences", recherche de TARTANPION Alexandre et suppression du coureur. Ce que l'utilisateur attend est un message "Suppression impossible : coureur déjà engagé sur une course". Bug : l'écran est grisé et un icone tourne indéfiniment au centre de l'écran. Aucun message, situation bloqué sur cet écran. Lorsque on va sur un autre menu et que l'on revient sur l'annuaire des licences, l'écran grisé et l'icone s'affiche quelques secondes. TARTANPION Alexandre existe toujours dans la base.

**Comment by dngconsulting** [comment]
Bien vu, mauvaise gestion du message d'erreur qui est renvoyé lorsque tu supprimes le coureur engagé.
